- name: Create backup directory if defined
  file:
    path: "{{ item.backup_directory }}"
    owner: "{{ barman_user }}"
    mode: 0770
    state: directory
    recurse: yes
  with_items: "{{ barman_server_configuration }}"
  when: item.backup_directory is defined

- name: Setup Barman Config
  template:
    src: barman.conf.j2
    dest: "/etc/barman.conf"
    mode: 0644

- name: Setup Barman Server Config
  template:
    src: server.conf.j2
    dest: "{{ barman_server_config_files_directory }}/{{ item.name }}.conf"
    mode: 0644
  with_items: "{{ barman_server_configuration | default([]) }}"

- name: Create slot for Barman
  shell: /usr/bin/barman receive-wal --create-slot {{ item.name }}
  ignore_errors: yes
  become: true
  become_user: "{{ barman_user }}"
  with_items: "{{ barman_server_configuration }}"
  when:
    - item.backup_method == "postgres"

- name: Create pgpass file
  template:
    src: pgpass.j2
    dest: "{{ barman_home }}/.pgpass"
    owner: "{{ barman_user }}"
    mode: 0600
